import os

HYDRA_BASE_URL = os.environ["HYDRA_BASE_URL"]
HYDRA_USERNAME = os.environ["HYDRA_USERNAME"]
HYDRA_PASSWORD = os.environ["HYDRA_PASSWORD"]
HYDRA_ENVIRONMENT = os.environ["HYDRA_ENVIRONMENT"]
